# fly.toml app configuration file generated for elaine-ma-backend on 2023-07-13T23:15:33-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "elaine-ma-backend"
primary_region = "dfw"

[http_service]
  internal_port = 1337
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
