"use client";
// These styles apply to every route in the application
import "../../dist/output.css";

import { Cinzel } from "next/font/google";
import Header from "../components/Header";
import Footer from "../components/Footer";
import { useEffect } from "react";
const cinzel = Cinzel({ subsets: ["latin"] });

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
	useEffect(() => {
		require("bootstrap/dist/js/bootstrap.bundle.min.js");
	}, []);
	return (
		<html lang="en" className={cinzel.className}>
			<body className="bg-black text-amber-400 container mx-auto">
				<Header />
				<main>{children}</main>
				<Footer />
			</body>
		</html>
	);
}
